modLoader="javafml"
loaderVersion="[41,)"
license="CC BY-NC-ND 4.0"
showAsResourcePack=false

[[mods]]
modId="explorations"
version="1.19 - 1.2"
displayName="Explorations+"
displayURL="https://www.curseforge.com/minecraft/mc-mods/explorations"
#logoFile="examplemod.png"
credits="Thanks to TelepathicGrunt for his StructureTutorialMod"
authors="Buecher_wurm"
description='''adds more vanilla style structures to the game'''

[[dependencies.explorations]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.explorations]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
