modLoader="javafml"
loaderVersion="[37,)"
license="CC BY-NC-ND 4.0"
showAsResourcePack=false

[[mods]]
modId="explorations"
version="1.17.1 - 1.0.0"
displayName="Explorations+"
displayURL="https://www.curseforge.com/minecraft/mc-mods/explorations"
#logoFile="examplemod.png"
#credits="Thanks for this example mod goes to Java"
authors="Buecher_wurm"
description='''adds more vanilla style structures to the game'''

[[dependencies.explorations]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.explorations]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
