plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version '[7.0.17,8)'
}

jar.manifest.attributes.put("MixinConfigs", "${mod_id}.mixins.json")

minecraft {
    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir('run')

            args "--mixin.config=${mod_id}.mixins.json"
            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
            systemProperty 'forge.enabledGameTestNamespaces', "${mod_id}"
        }

        register('client')

        register('server') {
            args '--nogui'
        }
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    maven {  url = "https://repo.spongepowered.org/maven" }
    mavenCentral()
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0.5'
    annotationProcessor("org.spongepowered:mixin:0.8.7:processor")

    compileOnly group: 'com.google.auto.service', name: 'auto-service', version: auto_service_version
    annotationProcessor group: 'com.google.auto.service', name: 'auto-service', version: auto_service_version
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}
