plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version '[7.0.17,8)'
    id 'org.spongepowered.mixin' version '0.8.5'
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")
    config("${mod_id}.mixins.json")
}
jar.manifest.attributes.put("MixinConfigs", "${mod_id}.mixins.json")

minecraft {
    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir('run')

            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
            systemProperty 'forge.enabledGameTestNamespaces', 'examplemod'
        }

        register('client')

        register('server') {
            args '--nogui'
        }
    }
}

repositories {
    minecraft.mavenizer(it) // In Kotlin, it = this
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
    maven {
        name = 'Sponge'
        url = uri('https://repo.spongepowered.org/repository/maven-public')
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0.5'
    annotationProcessor("org.spongepowered:mixin:0.8.5:processor")

    compileOnly group: 'com.google.auto.service', name: 'auto-service', version: auto_service_version
    annotationProcessor group: 'com.google.auto.service', name: 'auto-service', version: auto_service_version
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}
